-- AUTO-GENERATED by scripts/generate-craft-skills.mjs — do not edit.
-- Source: Wowhead TBC recipe spells (orange Difficulty / Requires Profession (N)).
-- Item tooltips do not include craft skill; only recipe pages do.

local _, GQ = ...
GQ.CraftSkills = GQ.CraftSkills or {}

GQ.CraftSkills[29964] = { profession = "Leatherworking", skill = 260, spellId = 36074 }
